### ISSUE TITLE
Requirements.txt Giving errors

### ISSUE THREAD

**Issue by Dhanasekhar-EEE** [HarryPham0123/YOLOv3-object-detection#2]
Requirements.txt Giving errors,
![REQFB](https://user-images.githubusercontent.com/60638679/142732544-020fa16a-3c48-45fd-8280-7c2b12cf57d9.PNG)

**Comment by HarryPham0123** [comment]
This requirement.txt is design for running interminal of python IDE. If you're using notebook, you can try
`import numpy as np`
`pip install opencv-python`
`pip install. tensorflow`

**Comment by Dhanasekhar-EEE** [comment]
Okay, Thnx; I have figured it put Already
