### ISSUE TITLE
Darknet package issue.

### ISSUE THREAD

**Issue by Dhanasekhar-EEE** [HarryPham0123/YOLOv3-object-detection#4]
Darknet package issue.
![DNFB](https://user-images.githubusercontent.com/60638679/142733441-89e42fab-1796-4e25-b577-d9c753d79b66.PNG)

**Comment by HarryPham0123** [comment]
It seems like the "Darknet53_Feature_Extraction" is from folder "Model_architecture". You can use copy the functions directly into your notebook

**Comment by Dhanasekhar-EEE** [comment]
> It seems like the "Darknet53_Feature_Extraction" is from folder "Model_architecture". You can copy the functions directly into your notebook

Sir, i figured it out... i cloned ur repository in G-colab,
and imported everything, 
but testing phase was failed,
i mean YOLO camera,Video, giving errors.. Like 'python' was not defined, @HarryPham0123 please help me to figure this out...
                                                                                                                                                            Thank you;
                                                                                                                                         God Of Destruction (@Dhanasekhar-EEE);

**Comment by HarryPham0123** [comment]
I did this project in Pycharm which is a Python IDE. Using this project in colab might have issue relating to cv2. 
Let's try clone the project to your computer and open the anaconda terminal, move to the clone folder & following the instruction in README

**Comment by Dhanasekhar-EEE** [comment]
> Hi @Dhanasekhar-EEE, I did this project in Pycharm which is a Python IDE. Using this project in colab might have issue relating to cv2. Let's try clone the project to your computer and open the anaconda terminal, move to the clone folder & following the instruction in README. If it still not works, please wait for 1 or 2 days later, I will create an instruction notebook for this project. Sorry for the inconvenience

@HarryPham0123, thank you for responding quickly.
I have pycharm installed in my Laptop....
I will try the project in PyCharm...
And i am waiting for the Instruction Notebook,Till then i will work with Readme...
